/*
 *
 * App constants
 *
 */

export const DEFAULT_ACTION = 'DEFAULT_ACTION';

export const GET_USER_ACTION_REQUEST = 'GET_USER_ACTION_REQUEST';
export const GET_USER_ACTION_SUCCESS = 'GET_USER_ACTION_SUCCESS';
export const GET_USER_ACTION_FAILURE = 'GET_USER_ACTION_FAILURE';

export const GET_MATCHES_ACTION_REQUEST = 'GET_MATCHES_ACTION_REQUEST';
export const GET_MATCHES_ACTION_SUCCESS = 'GET_MATCHES_ACTION_SUCCESS';
export const GET_MATCHES_ACTION_FAILURE = 'GET_MATCHES_ACTION_FAILURE';

export const GET_FILTER_REQUEST = 'GET_FILTER_REQUEST';
export const GET_FILTER_SUCCESS = 'GET_FILTER_SUCCESS';
export const GET_FILTER_FAILURE = 'GET_FILTER_FAILURE';

export const APPLY_FILTER_REQUEST = 'APPLY_FILTER_REQUEST';
export const APPLY_FILTER_SUCCESS = 'APPLY_FILTER_SUCCESS';
export const APPLY_FILTER_FAILURE = 'APPLY_FILTER_FAILURE';